### ISSUE TITLE
add info and warning

### ISSUE THREAD

**Issue by mybigman** [sujit-baniya/flash#3]
Since we have `WithSuccess()` and `WithError()` are you able to add the following?

`WithInfo()` and `WithWarn()`

By doing this it enables it to work well with a lot of `css frameworks` that support these alerts.

Thanks

**Comment by sujit-baniya** [comment]
@mybigman Added the functions. Please check latest commit: https://github.com/sujit-baniya/flash/tree/v0.1.5
