### ISSUE TITLE
cookie samesite

### ISSUE THREAD

**Issue by mybigman** [sujit-baniya/flash#5]
Can you please add samesite lax to cookie please or make is configurable defaulting to lax.

```
Cookie “f-Flash” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

Could you also lowercase the `-Flash` (cookie name) please?

**Comment by mybigman** [comment]
looks like you change `-Flash` to lowercase now which is appreciated.

This package no longer works unless I change your cookie code to set/get `SameSite=Lax`

I am not sure if its because of a browser upgrade or not, could you please configure to lax?

**Comment by sujit-baniya** [comment]
Hi @mybigman 
Let me check it today

**Comment by sujit-baniya** [comment]
@mybigman 
Please check https://github.com/sujit-baniya/flash/releases/tag/v0.1.7

**Comment by mybigman** [comment]
thanks mate... seems all good now.
